inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/20220912024024_devise_token_auth_create_users.rb"

Style/HashSyntax:
  Exclude:
    - "db/migrate/20220912024024_devise_token_auth_create_users.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/20220912024024_devise_token_auth_create_users.rb"

Style/SymbolArray:
  Exclude:
    - "db/migrate/20220912024024_devise_token_auth_create_users.rb"

Layout/TrailingWhitespace:
  Exclude:
    - "db/migrate/20220912024024_devise_token_auth_create_users.rb"

require:
  - rubocop-rails
  - rubocop-rspec

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "app/channels/application_cable/channel.rb"
    - "app/channels/application_cable/connection.rb"
    - "config/application.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
