inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "app/channels/application_cable/channel.rb"
    - "app/channels/application_cable/connection.rb"
    - "config/application.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
